<h1><?php echo $this->translate('Customers'); ?></h1>
<p><?php echo $this->translate('An overview of all customers.'); ?></p>

<table class="table">
    <tr>
        <th><?php echo $this->translate('Name'); ?></th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($customers as $customer) : ?>
        <tr>
            <td>
                <a href="<?php echo $this->url('customer',array('action'=>'view','id'=>$customer->id)); ?>">
                    <?php echo $this->escapeHtml($customer->name); ?>
                </a>
            </td>
            <td>
                <a href="<?php echo $this->url('customer',
                    array('action'=>'edit', 'id' => $customer->id)); ?>"><?php echo $this->translate('Edit'); ?></a>
                <a href="<?php echo $this->url('customer',
                    array('action'=>'delete', 'id' => $customer->id)); ?>"><?php echo $this->translate('Delete'); ?></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
