<h1>
    <a href="<?php echo $this->url('customer') ?>"><?php echo $this->translate('Customers')?></a>
    <span>></span>
    <span><?php echo $this->escapeHtml($customer->name); ?></span>
</h1>

<table class="table">
    <tr>
        <th><?php echo $this->translate('Projects'); ?></th>
    </tr>
    <?php foreach ($projects as $project) : ?>
        <tr>
            <td>
                <a href="<?php echo $this->url('project',array('action'=>'view','id'=>$project->id)); ?>">
                    <?php echo $this->escapeHtml($project->name); ?>
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
