<h1><?php echo $this->translate('Add credential'); ?></h1>
<p><?php echo $this->translate('Add a new credential'); ?></p>

<table class="table">
    <tr>
        <th><?php echo $this->translate('Project'); ?></th>
        <td><input type="text" /></td>
    </tr>
    
    <tr>
        <th><?php echo $this->translate('Category'); ?></th>
        <td><input type="text" /></td>
    </tr>
    
    <tr>
        <th><?php echo $this->translate('Cluster'); ?></th>
        <td><input type="text" /></td>
    </tr>
    
    <tr>
        <th><?php echo $this->translate('Server'); ?></th>
        <td><input type="text" /></td>
    </tr>
    
    <tr>
        <th><?php echo $this->translate('Notes'); ?></th>
        <td><input type="text" /></td>
    </tr>
    
    <tr>
        <th><?php echo $this->translate('URL'); ?></th>
        <td><input type="text" /></td>
    </tr>
    
    <tr>
        <th><?php echo $this->translate('Username'); ?></th>
        <td><input type="text" /></td>
    </tr>
    
    <tr>
        <th><?php echo $this->translate('Password'); ?></th>
        <td><input type="text" /></td>
    </tr>
</table>
