<h1><?php echo $this->translate('Add credential'); ?></h1>
<p><?php echo $this->translate('Add a new credential'); ?></p>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('credential', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('username'));
echo $this->formRow($form->get('password'));
echo $this->formRow($form->get('url'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();