<h1><?php echo $this->translate('Credentials'); ?></h1>
<p><?php echo $this->translate('An overview of all credentials.'); ?></p>

<table class="table">
    <tr>
        <th><?php echo $this->translate('ID'); ?></th>
        <th><?php echo $this->translate('Username'); ?></th>
        <th><?php echo $this->translate('Password'); ?></th>
        <th><?php echo $this->translate('URL'); ?></th>
        <th><?php echo $this->translate('Actions'); ?></th>
    </tr>
    <?php foreach ($credentials as $credential) : ?>
        <tr>
            <td><?php echo $credential->id; ?></td>
            <td>
                <a href="<?php echo $this->url('credential',array('action'=>'view','id'=>$credential->id)); ?>">
                    <?php echo $this->escapeHtml($credential->username); ?>
                </a>
            </td>
            <td>
                 <?php echo $this->escapeHtml($credential->password); ?>
            </td>
            <td>
                <a href="<?php echo $this->escapeHtml($credential->url); ?>" target="_blank">
                    <?php echo $this->escapeHtml($credential->url); ?>
                </a>
            </td>
            <td>
                <a href="<?php echo $this->url('credential',
                    array('action'=>'edit', 'id' => $project->id)); ?>"><?php echo $this->translate('Edit'); ?></a>
                <a href="<?php echo $this->url('credential',
                    array('action'=>'delete', 'id' => $project->id)); ?>"><?php echo $this->translate('Delete'); ?></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
