<h1><?php echo $this->translate('Projects'); ?></h1>
<p><?php echo $this->translate('An overview of all projects.'); ?></p>

<table class="table">
    <tr>
        <th><?php echo $this->translate('Number'); ?></th>
        <th><?php echo $this->translate('Name'); ?></th>
        <th><?php echo $this->translate('Url'); ?></th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($projects as $project) : ?>
        <tr>
            <td><?php echo $project->id; ?></td>
            <td>
                <a href="<?php echo $this->url('project',array('action'=>'view','id'=>$project->id)); ?>">
                    <?php echo $this->escapeHtml($project->name); ?>
                </a>
            </td>
            <td>
                <a href="<?php echo $this->escapeHtml($project->url); ?>" target="_blank">
                    <?php echo $this->escapeHtml($project->url); ?>
                </a>
            </td>
            <td>
                <a href="<?php echo $this->url('project',
                    array('action'=>'edit', 'id' => $project->id)); ?>"><?php echo $this->translate('Edit'); ?></a>
                <a href="<?php echo $this->url('project',
                    array('action'=>'delete', 'id' => $project->id)); ?>"><?php echo $this->translate('Delete'); ?></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
