<div class="hero-unit">
    <h1><?php echo sprintf($this->translate('%sPacman V2%s Projects'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo $this->translate('An overview of all the projects') ?></p>
</div>

<div class="row">

    <div class="span4">
        <p>
            <ul>
                <?php
                    foreach ($projects as $project) {
                        echo '<li><a href="'.$this->url('project',array('action'=>'view','id'=>$project->id)).'">'.$project->name.'</a></li>';
                    }
                ?>

            </ul>
        </p>
    </div>

</div>