<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Pacman V2'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/jquery-1.8.2.min.js')
                                      ->appendFile($this->basePath() . '/js/bootstrap.min.js') ?>
    </head>
    <body>
	
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Pacman V2') ?></a>
                    <div class="nav-collapse">
                        <ul class="nav">
                            <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        </ul>
						<ul class="nav pull-right">
						
							<form class="navbar-search pull-left" action="">
								<input type="text" class="search-query span2" placeholder="<?php echo $this->translate('Search Pacman') ?>">
							</form>
							
						  <li class="divider-vertical"></li>
						  
						  <li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->zfcUserDisplayName() ?> <b class="caret"></b></a>
							<ul class="dropdown-menu">
							  <li><a href="<?php echo $this->url('zfcuser') ?>"><?php echo $this->translate('My profile'); ?></a></li>
							  <li class="divider"></li>
							  <li><a href="<?php echo $this->url('zfcuser/changeemail') ?>"><?php echo $this->translate('Edit email'); ?></a></li>
							  <li><a href="<?php echo $this->url('zfcuser/changepassword') ?>"><?php echo $this->translate('Edit password'); ?></a></li>
							  
							</ul>
						  </li>
						</ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2012 Enrise. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
